******************* PART 1 CardValidatorTest 34 testcases *********************
*************COMPILATION ERROR*******************
tests/csu/csci325/CardValidatorTest.java:297: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:318: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:338: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:358: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:378: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:398: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:418: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:440: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:446: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:452: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:478: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:499: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:519: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:539: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:559: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:579: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:599: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:619: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:640: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:660: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:680: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:700: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:720: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
tests/csu/csci325/CardValidatorTest.java:740: error: exception MaxAttemptsExceededException is never thrown in body of corresponding try statement
        catch (MaxAttemptsExceededException e) {
        ^
24 errors
Compilation errors, please fix...
******************* PART 2 AddressVerificationTest - 18 testcases *********************
JUnit version 4.12
.checkStateZip2 - (invalid) 30301
InvalidAddressException thrown/caught appropriately.
.checkStateZip3 - (invalid) GA
InvalidAddressException thrown/caught appropriately.
.checkStateZip4 - (invalid)Georgia 30301
InvalidAddressException thrown/caught appropriately.
.checkCity - (invalid) W
InvalidAddressException thrown/caught appropriately.
.validateAddress - (valid) 123 OldBirch Lane, Wren, SC 29673
.checkFormat - (valid) 123 OldBirch, Wren, SC 29673
.checkStreetAdd - (invalid) OldBirch
InvalidAddressException thrown/caught appropriately.
.checkStreetAdd - (invalid) Old Birch
InvalidAddressException thrown/caught appropriately.
.checkStreetAdd - (invalid) 123 B
InvalidAddressException thrown/caught appropriately.
.checkStreetAdd - (valid) 123 OldBirch
.checkFormat - (invalid) 123 OldBirch, Wren
InvalidAddressException thrown/caught appropriately.
.checkFormat - (invalid) 123 OldBirch, Wren, SC, 29673
InvalidAddressException thrown/caught appropriately.
.validateAddress - (invalid) 123 OldBirch Lane, 29673
You have entered an invalid address, goodbye.
E.validateAddress - (invalid) OldBirch, Wren, SC, 29673
You have entered an invalid address, goodbye.
The street address portion is not of the form: HouseNumber StreetName.
The state and zip portion is not in the correct form.
.validateAddress - (invalid) 123 OldBirch, W, SC 29673
The city name portion is not in the correct form.
E.validateAddress - (invalid) 123 OldBirch, Wren, 29673
The state and zip portion is not in the correct form.
.checkCity - (valid) Wren
E.checkStateZip - (valid) GA 30301
E
Time: 0.02
There were 4 failures:
1) testValidateAddress2(csu.csci325.AddressVerificationTest)
java.lang.ArrayIndexOutOfBoundsException: 2
	at csu.csci325.AddressVerification.validateAddress(AddressVerification.java:77)
	at csu.csci325.AddressVerificationTest.testValidateAddress2(AddressVerificationTest.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
2) testValidateAddress4(csu.csci325.AddressVerificationTest)
java.lang.AssertionError: expected:<false> but was:<true>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at csu.csci325.AddressVerificationTest.testValidateAddress4(AddressVerificationTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
3) testCheckCity(csu.csci325.AddressVerificationTest)
csu.csci325.InvalidAddressException: You have entered an invalid city, goodbye.
	at csu.csci325.AddressVerification.checkCity(AddressVerification.java:147)
	at csu.csci325.AddressVerificationTest.testCheckCity(AddressVerificationTest.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
4) testCheckStateZip(csu.csci325.AddressVerificationTest)
csu.csci325.InvalidAddressException: You have entered an invalid state, goodbye.
	at csu.csci325.AddressVerification.checkStateZip(AddressVerification.java:172)
	at csu.csci325.AddressVerificationTest.testCheckStateZip(AddressVerificationTest.java:249)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)

FAILURES!!!
Tests run: 18,  Failures: 4

+ 27.195 pts of 35.000
Total grade so far: 27.195
Auto-grader grade: 27.195
*****************Finished lab07****************
